# Generated by Django 2.2.16 on 2022-10-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221013_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
